baseurl = "https://blog.burugu.xyz/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # either light or dark
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # reading time in minutes

  showReadingTime = true

  # blog description
  description = "Writing about code, taming computers and some ramblings on the side."

[languages]
  [languages.en]
    title = "Captain's log"
    subtitle = ""
    keywords = "blog tech"
    copyright = '''
      <div>
      <p>To submit an erratum create an issue <a target="_blank" rel="noopener noreferrer" href="https://github.com/Burugux/blog/issues/new">here</a>.</p>
      <p>&copy; 2019 Leslie Burugu &middot; Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a></p>
    '''
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Captain's log"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "Github"
        name = "Github"
        url = "https://github.com/burugux"  
      [[languages.en.menu.main]]
        name = "Linkedin"
        identifier = "linkedin"
        url = "https://www.linkedin.com/in/leslie-burugu/" 
      [[languages.en.menu.main]]
        name = "Keybase"
        identifier = "keybase"
        url = "https://keybase.io/burugu"  