#!/usr/bin/bash

# Creates new hugo posts

hugo version > /dev/null 2>&1

if [ $? -eq 0 ]; then
    if [ "$1" == "" ]; then
        echo "Invalid post name. Try: ./new my-post"
        exit 1
    else
        path="posts/$1.md"
        hugo new ${path}
    fi
else
    echo "Hugo is not installed. Get it at https://gohugo.io/"
    exit 1
fi

code -v > /dev/null 2>&1

if [ $? -eq 0 ]; then
    code .
fi